### PR TITLE
Update modules

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
granite -> 5.2.1
elementary-icons -> 5.0.1
vala -> 0.40.11

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Please don't merge this. The latest version of granite causes some issues with upstream adding a new dependency on wingpanel :/

**Comment by lsahn-gh** [comment]
Granite 5.2.2 looks good to me.  
What's the matter with it exactly?

**Comment by bilelmoussaoui** [comment]
@memnoth this is the issue I was talking about https://github.com/elementary/granite/issues/249

**Comment by lsahn-gh** [comment]
What do you think of this solution?

We only put ``https://github.com/elementary/wingpanel-indicator-datetime/blob/master/data/io.elementary.desktop.wingpanel.datetime.gschema.xml`` in ``${datadir}/glib-2.0/schemas/`` instead of installing wingpanel as well. Then we do not need to wait granite to fix it.  
Of course, we might have to update the file as long as granite is updated, but IMO it is better than stay in old version.

**Comment by bilelmoussaoui** [comment]
Yeah, this can be done in order to fix it. Does the new granite version improve any functionalities?

**Comment by lsahn-gh** [comment]
There are between 5.2.1 and 5.2.2. https://github.com/elementary/granite/pull/252
Also, about switched to meson build system.

**Comment by bilelmoussaoui** [comment]
Alright, will patch things until upstream solve the issue

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by lsahn-gh** [comment]
That's my fault. Granite 5.2.2 has CMake build system yet.
I should've examined it.
I'm really sorry about that.

**Comment by bilelmoussaoui** [comment]
bot, build

**Pull request merged**
